___assertEqual(+False, 0)
___assertIsNot(+False, False)
___assertEqual(-False, 0)
___assertIsNot(-False, False)
___assertEqual(abs(False), 0)
___assertIsNot(abs(False), False)
___assertEqual(+True, 1)
___assertIsNot(+True, True)
___assertEqual(-True, -1)
___assertEqual(abs(True), 1)
___assertIsNot(abs(True), True)
___assertEqual(~False, -1)
___assertEqual(~True, -2)

___assertEqual(False+2, 2)
___assertEqual(True+2, 3)
___assertEqual(2+False, 2)
___assertEqual(2+True, 3)

___assertEqual(False+False, 0)
___assertIsNot(False+False, False)
___assertEqual(False+True, 1)
___assertIsNot(False+True, True)
___assertEqual(True+False, 1)
___assertIsNot(True+False, True)
___assertEqual(True+True, 2)

___assertEqual(True-True, 0)
___assertIsNot(True-True, False)
___assertEqual(False-False, 0)
___assertIsNot(False-False, False)
___assertEqual(True-False, 1)
___assertIsNot(True-False, True)
___assertEqual(False-True, -1)

___assertEqual(True*1, 1)
___assertEqual(False*1, 0)
___assertIsNot(False*1, False)

___assertEqual(True/1, 1)
___assertIsNot(True/1, True)
___assertEqual(False/1, 0)
___assertIsNot(False/1, False)
