___assertIs(bool(10), True)
___assertIs(bool(1), True)
___assertIs(bool(-1), True)
___assertIs(bool(0), False)
___assertIs(bool("hello"), True)
___assertIs(bool(""), False)
___assertIs(bool(), False)
