___assertEqual(list(range(3)), [0, 1, 2])
___assertEqual(list(range(1, 5)), [1, 2, 3, 4])
___assertEqual(list(range(0)), [])
___assertEqual(list(range(-3)), [])
___assertEqual(list(range(1, 10, 3)), [1, 4, 7])
___assertEqual(list(range(5, -5, -3)), [5, 2, -1, -4])
